# Generated by Django 3.1.4 on 2021-01-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210105_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_preview',
            field=models.TextField(null=True, verbose_name='Превью содержания'),
        ),
    ]
