# Generated by Django 3.1.4 on 2021-01-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210105_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_preview',
            field=models.TextField(max_length=140, null=True, verbose_name='Превью содержания'),
        ),
    ]
