# Generated by Django 3.1.4 on 2021-01-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210105_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_preview',
            field=models.TextField(max_length=120, null=True, verbose_name='Превью содержания'),
        ),
    ]
