# Generated by Django 3.1.5 on 2021-01-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
    ]
